version: "3.7"
services:
  app:
    build:
      args:
        user: kraker
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kraker
    container_name: kraker-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kraker-network

  db:
    image: mysql:5.7
    container_name: kraker-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kraker
      MYSQL_ROOT_PASSWORD: kraker
      MYSQL_PASSWORD: kraker
      MYSQL_USER: kraker
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - kraker-network

  nginx:
    image: nginx:alpine
    container_name: kraker-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - kraker-network

networks:
  kraker-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
